### ISSUE TITLE
Image outdated

### ISSUE THREAD

**Issue by paoliniluis** [CircleCI-Public/cimg-clojure#11]
Will this image be updated some time? Clojure is now in 1.10.3 while this image is still in 1.10.1

**Comment by felicianotech** [comment]
Hi. This image is "still" in beta. It has not reaches production/stable status yet thus why it isn't getting the attention it deserves. So, I can publish new releases if you'd like, just keep in mind we don't consider it stable yet. If you need a stable version right now, we suggest using the older version of this image, `circleci/clojure`.

One of the reasons for this is feedback we've received that a Lein install shouldn't be the default going forward but using the install method from the docs: https://clojure.org/guides/getting_started#_installation_on_linux

Do you have an opinion here and what you would like to see for this image?

**Comment by paoliniluis** [comment]
Thanks for the quick reply. I would like to see an extremely slim image that has the latest Clojure version. For devs, it would be really good if everything is pulled from your Docker registries and also don't create custom images

**Comment by paoliniluis** [comment]
Adding something: CLI toos for the clojure images would be great

**Comment by paoliniluis** [comment]
Adding one thing more after using the clojure image. It would be awesome if you could have in a slim image:
- clojure
- clojure CLI
- Leinengen

and alternatives for node and browsers

thanks!

**Comment by Limess** [comment]
+1 For having all options pre-installed (many shops including ours still use Leinengen) or at least providing an option like the official Clojure Docker image.

It'd be great so see some update on this, else we're going to need to start looking at rolling our own base images soon.

**Comment by felicianotech** [comment]
The beta has been rebooted. There's a brand new beta image for v1.10.3 with a different build process. Hopefully it has what you need. Please check out the image and leave feedback in a new Issue or in the [CircleCI Discuss announcement post](https://discuss.circleci.com/t/next-gen-clojure-convenience-image-beta/42607).

Short summary, we're attempting clj and lein in the same image. If that doesn't work, then we will offer build as variants. Either way, but install options will be available for this image.
