### ISSUE TITLE
Suggestion for variants based on Java 8, 11 and 17

### ISSUE THREAD

**Issue by alanjclark** [CircleCI-Public/cimg-clojure#13]
Request from customer:

> Variants of the image that are based on Java 8, 11, and 17 would be really useful for us, as unfortunately we have some other components that we need to run in the container that still need Java 8. And we’d like to avoid having to maintain our own image if possible!

**Comment by felicianotech** [comment]
This will be done however we currently have a blocker. Either https://github.com/CircleCI-Public/cimg-shared/issues/51 or https://github.com/CircleCI-Public/cimg-shared/issues/52 need to be complete. Then this image can support multiple JDK versions.
