### ISSUE TITLE
"Orb-less" images to ensure feature compatibility with `circleci/clojure`

### ISSUE THREAD

**Issue by MrEbbinghaus** [CircleCI-Public/cimg-clojure#20]
The old `circleci/clojure` images with the `-browsers` variation had chrome (and other browsers) installed, ready to go. 

These new images make use of CircleCI Orbs, making them impractical for usage outside of CircleCI. 

Another thing:
A common use case is running CLJS unit tests with Karma, requiring headless browsers, but not selenium. 

So maybe additional following tags would be a good addition?

```
-browser-chrome                ; with chrome installed
-browser-chrome-selenium       ; with chrome + selenium installed
```

**Comment by felicianotech** [comment]
I'll elaborate more soon, but just wanted to provide an update here that we are planning a change to how the browsers variant works. It won't be exactly like how it worked with legacy images, but somewhere in-between the two.

**Comment by felicianotech** [comment]
Note to self, this happens when OpenJDK images get updated.

**Comment by felicianotech** [comment]
We didn't need to wait for OpenJDK, was confusing this with the Clojure image.

---
This image, as of a week or two ago, now ships Chrome and Firefox in the browsers variant. This starts with the 1.14.1 and 1.14.2 based images. Moving forward, releases will contain a single browser version. Older and newer browser versions should still be installed via the orb.
