### ISSUE TITLE
Clojure image with Java 8

### ISSUE THREAD

**Issue by Tim-fors** [CircleCI-Public/cimg-clojure#26]
Hi, 

I noticed #13 was closed.  I followed the instructions in the readme with the parentSlug-parentTag but it looks like the java 8 cimg is not available or I'm doing something wrong? 

I get this error 

> Error response from daemon: manifest for cimg/clojure:1.10.1-openjdk-8.0 not found: manifest unknown: manifest unknown

 and trying to reference the image as 
```
docker: 
   - image: cimg/clojure:1.10.1-openjdk-8.0
```

**Comment by JalexChen** [comment]
Uh oh. Looks like this might be a bigger issue than expected rather than just respinning the images. I'm going to take a look into this.
