### ISSUE TITLE
Add JAVA_HOME/bin to PATH

### ISSUE THREAD

**Issue by lilactown** [CircleCI-Public/cimg-clojure#34]
One gotcha I found migrating from the `circleci/clojure` images to the images in this repo is that `JAVA_HOME/bin` isn't added to `PATH`, which makes a lot of our scripts that try to run e.g. `jar` fails.

We have a workaround, but it seems easy enough for backward compat to add it.

**Comment by felicianotech** [comment]
Seems fair. We'll get this scheduled.
