### ISSUE TITLE
Not getting the latest version of Nodejs

### ISSUE THREAD

**Issue by lilactown** [CircleCI-Public/cimg-clojure#40]
Troubleshooting some test failures when using the `cimg/clojure:1.11-openjdk-11.0-browsers` image led to discovering that the version of Nodejs is quite old

```
~/app $ node -v
v12.10.0
```
It looks like the image should download the latest LTS version based on the ALIASES file in `cimg-node`

https://github.com/CircleCI-Public/cimg-clojure/blob/891ce552c27ceeba426d872d444f92a04cdce9fa/1.11/node/Dockerfile#L9

However, the version currently in that file (v16) does not match what's installed.

**Comment by felicianotech** [comment]
Hi. There's a couple things to unpack here:

1. Once Convenience Images are built, they don't get re-published. So in this scenario, whichever version of Node.js that a Clojure image ships with, that's what it stays with.
2. If you need further customizing of Node.js in an image, the [Node.js Orb](https://circleci.com/developer/orbs/orb/circleci/node) should be used.
3. In this case, `1.11` is an alias tag so it will automatically point to the latest v1.11.x release out.
4. The specific tag provided, `cimg/clojure:1.11-openjdk-11.0-browsers`, contains Node.js v16.15.0: https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/810/workflows/c597bdf3-44fc-491a-afa2-9d67e9aca048/jobs/1822

Are you checking the image locally? If so, perhaps a `docker pull` is needed to update your local image?

**Comment by lilactown** [comment]
I checked the image in CircleCI by sshing into the executor while it was running my tests.

Here's the output of "Spin up environment":

```
Starting container 485692797166.dkr.ecr.us-west-2.amazonaws.com/circle-ci/cljs-test:java-11-20220502
  image cache not found on this host, downloading 485692797166.dkr.ecr.us-west-2.amazonaws.com/circle-ci/cljs-test:java-11-20220502
java-11-20220502: Pulling from circle-ci/cljs-test

219afd04: Pulling fs layer 
60265e75: Pulling fs layer 
e40d0e61: Pulling fs layer 
7f502a07: Pulling fs layer 
b8c498aa: Pulling fs layer 
47e69698: Pulling fs layer 
203e8c30: Pulling fs layer 
540cbe0c: Pulling fs layer 
954aba43: Pulling fs layer 
2113b315: Pulling fs layer 
f137bf32: Pulling fs layer 
bb6f2368: Pulling fs layer 
077598d6: Pulling fs layer 
47e69698: Waiting fs layer 
b7de84c2: Pulling fs layer 
6e0bdd41: Pulling fs layer 
03e8c30: Waiting fs layer 
10cc43ca: Pulling fs layer 
2fc88562: Pulling fs layer 
917cfb52: Pulling fs layer 
Digest: sha256:f4bca44e68900558dab46f1af84db7ad560b96fd1dd7efd8676ede729bbf593204MB/9.204MBB
Status: Downloaded newer image for 485692797166.dkr.ecr.us-west-2.amazonaws.com/circle-ci/cljs-test:java-11-20220502
485692797166.dkr.ecr.us-west-2.amazonaws.com/circle-ci/cljs-test:java-11-20220502:
  using image 485692797166.dkr.ecr.us-west-2.amazonaws.com/circle-ci/cljs-test@sha256:f4bca44e68900558dab46f1af84db7ad560b96fd1dd7efd8676ede729bbf5932
  pull stats: download 745.9MiB in 39.837s (18.72MiB/s), extract 745.7MiB in 12.247s (60.89MiB/s)
  time to create container: 888ms
Time to upload agent and config: 406.391774ms
Time to start containers: 451.246286ms
```

**Comment by lilactown** [comment]
Wait a sec, that doesn't look like the right container...

**Comment by lilactown** [comment]
classic PEBKAC - turns out this job was using a different docker image and I didn't see it in the config. nevermind!
