### ISSUE TITLE
[bug report]

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/cimg-clojure#6]
Unable to use `checkout` command due to the following error:

> Directory (/home/circleci/project) you are trying to checkout to is not empty and not a git repository

image used:

> cimg/clojure:1.10
> cimg/clojure@sha256:b1e9fd2afba5fe38743550f45fee1baf8ffc65307a4c44c818fc7ec62661fb3d

SSHing into the job (which fails at checkout which is the first step), I can see there does appear to be a file in that directory. 

`~/project/target/stale/leiningen.core.classpath.extract-native-dependencies`

It seems these paths and the file within must be removed or relocated.

**Comment by felicianotech** [comment]
This will be fixed today.

**Comment by felicianotech** [comment]
@KyleTryon The fix has been deployed.
